### ISSUE TITLE
Bugs, sugestions

### ISSUE THREAD

**Issue by MendelssohnTW** [MendelssohnTW/robot.tw2#1]
Bugs, sugestions.

**Comment by xitiu** [comment]
O farm não está funcionando direito, o problema deve estar nas predefinições, ele não está contabilizando direito quantas tropas estão na cidade. Obrigado por ajudar.

**Comment by MendelssohnTW** [comment]
> O farm não está funcionando direito, o problema deve estar nas predefinições, ele não está contabilizando direito quantas tropas estão na cidade. Obrigado por ajudar.

Não entendi a sua questão. O farm envia todas as tropas da cidade dentro do limite de comandos setados na configuração. Se existe uma predefinição com 10 unidades e limite de 42 comandos ele enviará 420 unidades. Ou até quantas unidades estiverem na aldeia .

**Comment by xitiu** [comment]
![opera instantaneo_2019-03-07_111803_br tribalwars2 com](https://user-images.githubusercontent.com/14171858/53962809-c12c7b00-40ca-11e9-8ea3-350532a44518.png)
Olha a imagem por favor, eu tenho exércitos suficientes pra o script mandar farmar, mas ele não está enviando. Acredito que seja no ponto de encontro diz outra coisa.

**Comment by MendelssohnTW** [comment]
Existe uma configuração importante. Pra início de jogo ela faz com que a área de procura por aldeias seja pequena podendo não encontrar devido o nível do ponto de encontro ainda estar baixo. Esta configuração é o tempo máximo. O padrão atual está em 1 hora. sendo que será 30 minutos pra ir e mais 30 minutos pra voltar. Como em início de jogo as aldeias bárbaras ficam um pouco distante em relação a origem e nível do ponto de encontro é baixo o sistema não localiza tais aldeias. Oriento usar um tempo máximo de 3 horas com ponto de encontro até nível 3.

**Comment by MendelssohnTW** [comment]
Na tela de Farm ( Shift + F) você encontrará esta configuração. Podendo fazer mudança para somente uma predefinição, ou para todas as predefinições para a aldeia selecionada. Logo estarei adicionando mais uma opção que será mudar pra todas as predefinições de todas as aldeias.

**Comment by xitiu** [comment]
Ok, muito obrigado.

**Comment by MendelssohnTW** [comment]
Closed
