### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Arrau** [MendelssohnTW/robot.tw2#2]
"-ms-preload": {
		"backgroundScript": "backgroundScriptsAPIBridge.js",
		"contentScript": "contentScriptsAPIBridge.js"
	}

**Comment by Arrau** [comment]
Unrecognized manifest key '-ms-preload'.

**Comment by MendelssohnTW** [comment]
This error does not disturb anything. This object is only used when installed on Microsoft Edge.

**Comment by Arrau** [comment]
Thanks for the reply.
Also I haven't been able to start the script, the Ctrl Alt P key together doesn't work. Am I doing something wrong?

**Comment by MendelssohnTW** [comment]
Sorry, i'm choice for Shift + P. Because conflicts on TOR browsers.

**Comment by MendelssohnTW** [comment]
Thanks, for callback.

**Comment by Globotrotters** [comment]
Tem um bug que quando voce coloca ou ativa o autofarm para uma aldeia e para as outras não, ainda assim o bot faz ataque automatico nas aldeias que estão desativadas, e nesse mesmo modulo por assim dizer quando voce colocar o tempo maximo para tipo 03:30:00 , o bot muda esse valor para 03:24:04 ou para menos que isso, não sei se é bug ou um calculo automatico. Sou muito fã desse seu trabalho cara, eu só queria saber como funciona o Headquarter, eu nao soube configurar ele.

**Comment by MendelssohnTW** [comment]
Esses valores são calculados automáticos e arredondados baseados nos campos do percurso.
Com relação ao bug da sinalização de parada, já foi corrigido. Quando você faz motivação neste valores o próximo ciclo que respeitará a regra.

**Comment by MendelssohnTW** [comment]
No Headquarter voce configura os níveis a serem atingidos, e a sequência de priorização. O parâmetro flexível ou íntegro define a forma como será feito a sequência. No flexível eles evolui conforme a sequência e disponibilidade de recursos, sendo que analisa a pilha e se não for possível a evolução então para outra sequência. No íntegro ele só evolui o topo da sequência e aguarda recursos. Passando para ob outro edifício somente quando atingir o nível máximo setado deste. Existe também a reserva de slots para o trabalho, a reservas de recursos a ser mantido nas aldeias assim com as provisões. O ciclo é rodado em intervalos de uma hora ou após ser evoluído um edifício.

**Comment by MendelssohnTW** [comment]
Closed

**Comment by MendelssohnTW** [comment]
Resolvido
