### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by eksten** [MendelssohnTW/robot.tw2#4]
Hey,

Is it possible to get the instructions in english on how to install? 
when adding the extension is it from the folder "extensions" "app" ?

Or is it not run as an extension but something else? sorry for being dumb :)

The link for the extension on the first page does not work.

**Comment by MendelssohnTW** [comment]
You can download the zip file, unzip it somewhere and install it as an
extension.  Or you can download the unzipped files, put them in a folder
and install as an extension.  Only this.
After installing as an extension you must release it in Adblock.  Adblock
blocks because it already inserts script content on the page.

Em seg, 6 de jul de 2020 13:43, Olle <notifications@github.com> escreveu:

**Comment by eksten** [comment]
hmm.. got it working i belive. but i cant see any texts on the diffrent menues. i have all the buttons and stuff but nothing that explains what they do

**Comment by MendelssohnTW** [comment]
Shift + p, shortcut key.
There are no menus on screen.

Em seg, 6 de jul de 2020 13:59, Olle <notifications@github.com> escreveu:

**Comment by eksten** [comment]
yeah i get that, but when i enter for example the farm menu theres not text that tell me what the diffrent boxes/buttons do. 

So i see the menu but not what the diffrent settings is

**Comment by MendelssohnTW** [comment]
Clear cache browser's.
Restart your browser.

Em seg, 6 de jul de 2020 14:05, Olle <notifications@github.com> escreveu:

**Comment by eksten** [comment]
it didnt help, it looks like this https://imgur.com/a/pP3zMoZ

**Comment by MendelssohnTW** [comment]
This seems to be a problem with your translation.  Browser and game
language configuration.  Default is English.  But it doesn't have all the
game locations in the script.

Em seg, 6 de jul de 2020 14:13, Olle <notifications@github.com> escreveu:

**Comment by eksten** [comment]
yeah, that was the problem, thx man and great work with the script :)
