### ISSUE TITLE
Attack Bot not showing options for scheduling

### ISSUE THREAD

**Issue by aditrustagi** [MendelssohnTW/robot.tw2#5]
I am recently facing the issue where there is no option to schedule attacks using the attack bot. 
Similar thing for the spy option as well.

**Comment by MendelssohnTW** [comment]
Try clearing your browser cache

De: Adit Rustagi<mailto:notifications@github.com>
Enviado:quinta-feira, 9 de julho de 2020 06:19
Para: MendelssohnTW/robot.tw2<mailto:robot.tw2@noreply.github.com>
Cc:Subscribed<mailto:subscribed@noreply.github.com>
Assunto: [MendelssohnTW/robot.tw2] Attack Bot not showing options for scheduling (#5)


I am recently facing the issue where there is no option to schedule attacks using the attack bot.
Similar thing for the spy option as well.

**Comment by aditrustagi** [comment]
Well it doesn't help. I guess i will give it a while. Maybe some issue with the server or something.

**Comment by aditrustagi** [comment]
Hi Mendel,

It doesn't get rectified using clearing the cache.
A few other people I know who have access to your bot are also facing the
same issue.

Regards
Adit

**Comment by aditrustagi** [comment]
Market module is also no longer sending resources to other villages.

**Comment by MendelssohnTW** [comment]
Attack module returned to work?

Em ter, 21 de jul de 2020 11:37, Adit Rustagi <notifications@github.com>
escreveu:

**Comment by aditrustagi** [comment]
No not really. Attack module and market(sending resources) are not working.
