### ISSUE TITLE
Chrome wont load extension 

### ISSUE THREAD

**Issue by overflows1** [MendelssohnTW/robot.tw2#6]
Error message:
Cannot load extension with file or directory name _linux. Filenames starting with "_" are reserved for use by the system.
Could not load manifest.

**Comment by MendelssohnTW** [comment]
Have any files been renamed?  There are no files with system-reserved names.

**Comment by overflows1** [comment]
no name change.
I try re-download but https://github.com/MendelssohnTW/robot.tw2/raw/master/extension/app.zip is error 404

**Comment by MendelssohnTW** [comment]
https://github.com/MendelssohnTW/robot.tw2/raw/master/extension/app/app.zip

Link updated.

**Comment by overflows1** [comment]
thankyou fixed :)

**Comment by MendelssohnTW** [comment]
Solved
